=== phoebius/phoebius/base/share/Orm/Domain/Importer/Xml/abstract.dtd
<!--
 ************************************************************************************************
 * 
 * Phoebius Framework
 * 
 ************************************************************************************************
 * 
 * Copyright notice
 * 
 ************************************************************************************************
-->

<!-- 
Future releases:
================
 + Property type settings
 	<property name="counter" type="Integer">
	 	<typeSettings>
	 		<typeSetting name="size">11</typeSetting>
	 	</typeSettings>
	 </property>
 	<property name="money" type="Float">
	 	<typeSettings>
	 		<typeSetting name="precition">10</typeSetting>
	 		<typeSetting name="scale">5</typeSetting>
	 	</typeSettings>
	 </property>
-->

<!ELEMENT domain (entities*)>
<!ATTLIST domain
	name			CDATA #IMPLIED
	db-schema		CDATA #IMPLIED
>

<!ELEMENT entities (entity*)>

<!ELEMENT entity (properties*)>
<!ATTLIST entity
	name			ID #REQUIRED
	has-dao			(true|false) "true"
	db-schema		CDATA #IMPLIED
	db-table		CDATA #IMPLIED
>

<!ELEMENT properties (identifier?, property*, container*)>

<!-- If entity is identifierless then entity.has-dao should be specified explicitly -->
<!ELEMENT identifier EMPTY>
<!ATTLIST identifier
	name			CDATA "id"
	type			CDATA "AutoIntPropertyType"
	db-columns		CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
	name			CDATA #REQUIRED
	type			CDATA #REQUIRED
	visibility		(full|readonly|transparent) "full"
	unique			(true|false) "false"
	multiplicity	(zeroOrOne|exactlyOne) "exactlyOne"
	db-columns		CDATA #IMPLIED
>

<!-- 
Container works like a typical property except that:
 - it does not store a value, it only refers to a bunch of entities
 - its visibility is readonly
 - it is always not unique
 - relation (1:*, *:*) is determined by a referencing property type, e.g.: type=Entity refs=EntityProperty
 --> 
<!ELEMENT container EMPTY>
<!ATTLIST container
	name			CDATA #REQUIRED
	type			CDATA #REQUIRED
	refs			CDATA "id"
	db-columns		CDATA #IMPLIED
>

=== phoebius/phoebius/test/var/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * ***********************************************************************************************
 *
 * Phoebius Framework
 *
 * **********************************************************************************************
 *
 * Copyright (c) 2011 Scand Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 3 of the License, or (at your option) any later version.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program; if not, see <http://www.gnu.org/licenses/>.
 *
 *************************************************************************************************
-->

<!DOCTYPE domain SYSTEM "../../share/Orm/Domain/Meta/Xml/abstract.dtd">

<domain>
	<entities>
		<entity name="TestRemoteAddr" has-dao="false">
			<properties>
				<property name="mac" type="String" unique="true"/>
				<property name="ip" type="String"/>
			</properties>
		</entity>
		<entity name="TestUser" has-dao="true">
			<properties>
				<identifier/>
				<property name="name" type="String"/>
				<property name="remoteAddr" type="TestRemoteAddr" unique="true"/>
			</properties>
		</entity>
		<entity name="TestEntry" has-dao="true">
			<properties>
				<identifier/>
				<property name="title" type="String"/>
				<property name="author" type="TestUser"/>
			</properties>
		</entity>
		<entity name="TestComment" has-dao="true">
			<properties>
				<identifier />
				<property name="entry" type="TestEntry" />
				<property name="comment" type="String" />
				<property name="time" type="Timestamp" queryable="true" />
			</properties>
		</entity>
	</entities>
</domain>

=== phoebius/phoebius/base/share/Orm/Domain/Importer/Xml/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE domain SYSTEM "abstract.dtd">

<domain db-schema="default">
	<entities>
		<entity name="Post">
			<properties>
				<identifier />
				<property name="title" type="String" />
				<property name="text" type="String" />
				<property name="date" type="Date" />
			</properties>
		</entity>
		<entity name="Comment">
			<properties>
				<identifier />
				<property name="author" type="String" />
				<property name="text" type="String" />
				<property name="post" type="Post" />
				<property name="time" type="Timestamp" />
			</properties>
		</entity>
	</entities>
</domain>
